<?php

return [
  // Nav
  'nav_home' => 'Home',
  'nav_shop' => 'Shop',
  'nav_cart' => 'Cart',
  'nav_login' => 'Login',
  'nav_register' => 'Register',
  'nav_account' => 'My Account',
  'nav_admin' => 'Admin',
  'nav_logout' => 'Logout',
  'nav_policies' => 'Policies',

  // Home
  'home_hero_title' => 'Premium Fashion',
  'home_hero_subtitle' => 'Discover the latest trends in premium clothing',
  'home_hero_btn' => 'Shop Now',
  'home_featured' => 'Featured Products',
  'home_categories' => 'Shop by Category',
  'home_promotions' => 'Hot Deals',
  'home_new_collections' => 'New Collections',
  'home_brands' => 'Our Brands',
  'home_testimonials' => 'What Our Customers Say',
  'home_newsletter_title' => 'Stay in the Loop',
  'home_newsletter_subtitle' => 'Subscribe to get exclusive offers and new arrivals',
  'home_newsletter_placeholder' => 'Enter your email',
  'home_newsletter_btn' => 'Subscribe',
  'home_gallery' => 'Follow Us on Instagram',
  'home_gallery_empty' => 'No images yet. Add them in the admin panel.',

  // Shop
  'shop_title' => 'All Products',
  'shop_filter' => 'Filter by Category',
  'shop_all' => 'All',
  'shop_sort' => 'Sort by',
  'shop_sort_newest' => 'Newest',
  'shop_sort_best_sellers' => 'Best Sellers',
  'shop_sort_popularity' => 'Popularity',
  'shop_sort_price_asc' => 'Price: Low to High',
  'shop_sort_price_desc' => 'Price: High to Low',
  'shop_no_products' => 'No products found.',
  'shop_add_to_cart' => 'Add to Cart',
  'shop_view' => 'View Details',
  'shop_wishlist_add' => 'Add to Wishlist',
  'shop_wishlist_remove' => 'Remove from Wishlist',
  'shop_grid_view' => 'Grid View',
  'shop_list_view' => 'List View',
  'shop_price_range' => 'Price Range',
  'shop_min' => 'Min',
  'shop_max' => 'Max',
  'shop_filter_go' => 'Go',
  'shop_size' => 'Size',
  'shop_color' => 'Color',
  'shop_gender' => 'Gender',
  'shop_men' => 'Men',
  'shop_women' => 'Women',
  'shop_unisex' => 'Unisex',
  'shop_brand' => 'Brand',
  'shop_filters' => 'Filters',
  'shop_in_stock' => 'In Stock',
  'shop_on_sale' => 'On Sale',
  'shop_clear' => 'Clear',

  // Product
  'product_sale' => 'Sale',
  'product_new' => 'New',
  'product_sizes' => 'Sizes',
  'product_colors' => 'Colors',
  'product_quantity' => 'Quantity',
  'product_add_to_cart' => 'Add to Cart',
  'product_description' => 'Description',
  'product_details' => 'Details',
  'product_related' => 'You May Also Like',
  'product_out_of_stock' => 'Out of Stock',
  'product_select_size' => 'Select a size',
  'product_select_color' => 'Select a color',
  'product_in_stock' => 'In Stock',
  'product_stock_available' => 'Available',
  'product_low_stock' => 'Only %d left in stock',
  'product_material' => 'Material',
  'product_measurements' => 'Measurements',
  'product_size_chart' => 'Size Chart',
  'product_no_details' => 'No additional details available.',
  'product_share' => 'Share',
  'product_copy_link' => 'Copy Link',
  'product_reviews' => 'Reviews',
  'product_write_review' => 'Write a Review',
  'product_review_rating' => 'Rating',
  'product_review_name' => 'Your Name',
  'product_review_text' => 'Your Review',
  'product_review_submit' => 'Submit Review',
  'product_review_thanks' => 'Thank you for your review!',
  'product_review_rating_error' => 'Please select a rating.',
  'product_review_text_error' => 'Please write a review.',
  'product_review_name_error' => 'Please enter your name.',
  'product_review_already' => 'You have already reviewed this product.',
  'product_no_reviews' => 'No reviews yet. Be the first to review!',

  // Cart
  'cart_title' => 'Shopping Cart',
  'cart_empty' => 'Your cart is empty.',
  'cart_start_shopping' => 'Start Shopping',
  'cart_product' => 'Product',
  'cart_price' => 'Price',
  'cart_quantity' => 'Qty',
  'cart_total' => 'Total',
  'cart_remove' => 'Remove',
  'cart_subtotal' => 'Subtotal',
  'cart_shipping' => 'Shipping',
  'cart_free_shipping' => 'Free shipping on orders over :min!',
  'cart_total_to_pay' => 'Total',
  'cart_added' => 'Added to cart!',
  'cart_view' => 'View Cart',
  'cart_checkout' => 'Proceed to Checkout',
  'cart_continue' => 'Continue Shopping',
  'cart_updated' => 'Cart updated!',
  'cart_removed' => 'Item removed.',

  // Checkout
  'checkout_title' => 'Checkout',
  'checkout_shipping' => 'Shipping Information',
  'checkout_address' => 'Address',
  'checkout_city' => 'City',
  'checkout_zip' => 'ZIP Code',
  'checkout_order_summary' => 'Order Summary',
  'checkout_place_order' => 'Place Order',
  'checkout_success' => 'Order placed successfully!',
  'checkout_no_pending' => 'No pending order found. Please try again.',
  'checkout_login_required' => 'Please login to checkout.',
  'checkout_login_btn' => 'Login',

  // Order
  'order_number' => 'Order #:id',
  'order_number_short' => '#',
  'order_date' => 'Date',
  'order_status' => 'Status',
  'order_total' => 'Total',
  'order_items' => 'Items',
  'order_paid' => 'Paid',
  'order_pending' => 'Pending',
  'order_paid' => 'Paid',
  'order_cancelled' => 'Cancelled',
  'order_shipped' => 'Shipped',
  'order_delivered' => 'Delivered',
  'order_cancelled' => 'Cancelled',

  // Auth
  'auth_login_title' => 'Login',
  'auth_login_btn' => 'Login',
  'auth_register_title' => 'Create Account',
  'auth_register_btn' => 'Register',
  'auth_email' => 'Email',
  'auth_password' => 'Password',
  'auth_name' => 'Full Name',
  'auth_confirm_password' => 'Confirm Password',
  'auth_no_account' => "Don't have an account?",
  'auth_has_account' => 'Already have an account?',
  'auth_register_link' => 'Register here',
  'auth_login_link' => 'Login here',
  'auth_invalid' => 'Invalid email or password.',
  'auth_email_taken' => 'Email already registered.',
  'auth_passwords_mismatch' => 'Passwords do not match.',
  'auth_registered' => 'Account created successfully!',

  // Account
  'account_dashboard' => 'Dashboard',
  'account_orders' => 'My Orders',
  'account_profile' => 'Profile',
  'account_welcome' => 'Welcome, :name',
  'account_no_orders' => 'No orders yet.',
  'account_info' => 'Account Information',
  'account_email' => 'Email',
  'account_member_since' => 'Member since',
  'account_no_address' => 'No shipping address saved yet.',
  'account_wishlist' => 'Wishlist',
  'account_no_wishlist' => 'Your wishlist is empty.',

  // Admin
  'admin_dashboard' => 'Admin Dashboard',
  'admin_products' => 'Products',
  'admin_categories' => 'Categories',
  'admin_orders' => 'Orders',
  'admin_customers' => 'Customers',
  'admin_settings' => 'Settings',
  'admin_add' => 'Add New',
  'admin_add_product' => 'Add Product',
  'admin_edit' => 'Edit',
  'admin_delete' => 'Delete',
  'admin_save' => 'Save',
  'admin_cancel' => 'Cancel',
  'admin_confirm_delete' => 'Are you sure?',
  'admin_name' => 'Name',
  'admin_slug' => 'Slug',
  'admin_price' => 'Price',
  'admin_sale_price' => 'Sale Price',
  'admin_stock' => 'Stock',
  'admin_featured' => 'Featured',
  'admin_image' => 'Image URL',
  'admin_description' => 'Description',
  'admin_category' => 'Category',
  'admin_sizes' => 'Sizes (comma separated)',
  'admin_colors' => 'Colors (comma separated)',
  'admin_actions' => 'Actions',
  'admin_status' => 'Status',
  'admin_total' => 'Total',
  'admin_customer' => 'Customer',
  'admin_no_products' => 'No products yet.',
  'admin_no_categories' => 'No categories yet.',
  'admin_no_orders' => 'No orders yet.',
  'admin_no_customers' => 'No customers yet.',
  'admin_product_added' => 'Product added.',
  'admin_product_updated' => 'Product updated.',
  'admin_product_deleted' => 'Product deleted.',
  'admin_category_added' => 'Category added.',
  'admin_category_updated' => 'Category updated.',
  'admin_category_deleted' => 'Category deleted.',
  'admin_order_updated' => 'Order updated.',
  'admin_order_shipped' => 'Order marked as shipped and customer notified.',
  'admin_settings_saved' => 'Settings saved.',

  // Admin Settings
  'admin_settings_site_name' => 'Site Name',
  'admin_settings_logo' => 'Logo URL',
  'admin_settings_favicon' => 'Favicon URL',
  'admin_settings_primary_color' => 'Primary Color',
  'admin_settings_secondary_color' => 'Secondary Color',
  'admin_settings_seo_title' => 'SEO Title',
  'admin_settings_seo_description' => 'SEO Description',
  'admin_settings_seo_keywords' => 'SEO Keywords',
  'admin_settings_footer_text' => 'Footer Text',
  'admin_settings_currency' => 'Currency Symbol',
  'admin_settings_language' => 'Language',
  'admin_settings_items_per_page' => 'Items Per Page',
  'admin_settings_shipping_cost' => 'Shipping Cost',
  'admin_settings_free_shipping_min' => 'Free Shipping Minimum',
  'admin_settings_email' => 'Email (SMTP) Settings',

  // Inventory
  'admin_inventory' => 'Inventory',
  'admin_inventory_entries' => 'Entries',
  'admin_inventory_exits' => 'Exits',
  'admin_inventory_alerts' => 'Alerts',
  'admin_inventory_movements' => 'Movements',
  'admin_inventory_entry_add' => 'Register Stock Entry',
  'admin_inventory_exit_add' => 'Register Stock Exit',
  'admin_inventory_product' => 'Product',
  'admin_inventory_quantity' => 'Quantity',
  'admin_inventory_reason' => 'Reason',
  'admin_inventory_stock_before' => 'Before',
  'admin_inventory_stock_after' => 'After',
  'admin_inventory_status' => 'Status',
  'admin_inventory_ok' => 'OK',
  'admin_inventory_low' => 'Low',
  'admin_inventory_out' => 'Out of Stock',
  'admin_inventory_all_stocked' => 'All products are well-stocked!',
  'admin_inventory_no_movements' => 'No movements yet.',
  'admin_inventory_no_entries' => 'No entries yet.',
  'admin_inventory_no_exits' => 'No exits yet.',
  'admin_inventory_total_products' => 'Total Products',
  'admin_inventory_low_stock' => 'Low Stock',
  'admin_inventory_out_of_stock' => 'Out of Stock',
  'admin_inventory_last_movement' => 'Last Movement',
  'admin_inventory_search' => 'Search products...',
  'admin_inventory_add_stock' => 'Add Stock',
  'admin_inventory_remove_stock' => 'Remove Stock',
  'admin_inventory_entry_registered' => 'Stock entry registered.',
  'admin_inventory_exit_registered' => 'Stock exit registered.',
  'admin_inventory_insufficient' => 'Insufficient stock.',
  'admin_inventory_invalid' => 'Invalid product or quantity.',

  // Coupons
  'admin_coupons' => 'Coupons',
  'admin_coupon_new' => 'New Coupon',
  'admin_coupon_edit' => 'Edit Coupon',
  'admin_coupon_code' => 'Coupon Code',
  'admin_coupon_type' => 'Discount Type',
  'admin_coupon_value' => 'Value',
  'admin_coupon_min_amount' => 'Min Amount',
  'admin_coupon_max_discount' => 'Max Discount',
  'admin_coupon_usage_limit' => 'Usage Limit',
  'admin_coupon_expires' => 'Expires',
  'admin_coupon_active' => 'Active',
  'admin_coupon_inactive' => 'Inactive',
  'admin_coupon_created' => 'Coupon created.',
  'admin_coupon_updated' => 'Coupon updated.',
  'admin_coupon_deleted' => 'Coupon deleted.',
  'cart_coupon' => 'Coupon',
  'cart_coupon_placeholder' => 'Coupon code',
  'cart_coupon_apply' => 'Apply',
  'cart_coupon_applied' => 'Coupon applied!',
  'cart_coupon_remove' => 'Remove',
  'cart_coupon_empty' => 'Please enter a code.',
  'cart_coupon_invalid' => 'Invalid or expired coupon code.',
  'cart_discount' => 'Discount',

  // Shipping
  'admin_shipping' => 'Shipping',
  'admin_shipping_zones' => 'Zones',
  'admin_shipping_rates' => 'Rates',
  'admin_shipping_tracking' => 'Tracking',
  'admin_shipping_zone_name' => 'Zone Name',
  'admin_shipping_countries' => 'Countries',
  'admin_shipping_rate_name' => 'Rate Name',
  'admin_shipping_rate_type' => 'Type',
  'admin_shipping_rate_value' => 'Value',
  'admin_shipping_min_amount' => 'Min Amount',
  'admin_shipping_max_amount' => 'Max Amount',
  'admin_shipping_tracking_number' => 'Tracking Number',
  'admin_shipping_tracking_url' => 'Tracking URL',
  'admin_shipping_zone_created' => 'Zone created.',
  'admin_shipping_zone_updated' => 'Zone updated.',
  'admin_shipping_zone_deleted' => 'Zone deleted.',
  'admin_shipping_rate_created' => 'Rate created.',
  'admin_shipping_rate_updated' => 'Rate updated.',
  'admin_shipping_rate_deleted' => 'Rate deleted.',
  'admin_shipping_tracking_updated' => 'Tracking updated.',
  'order_tracking' => 'Tracking',
  'order_track_package' => 'Track Package',

  // Payments
  'admin_payments' => 'Payments',
  'admin_payments_transactions' => 'All Transactions',
  'admin_payments_refunded' => 'Refunded',
  'admin_payments_total_revenue' => 'Total Revenue',
  'admin_payments_transaction_count' => 'Transactions',
  'admin_payments_refunded_total' => 'Refunded',
  'admin_payments_refunded_count' => 'Refunded Orders',
  'admin_payments_refund' => 'Refund',
  'admin_payments_refund_amount' => 'Refund Amount',
  'admin_payments_refund_reason' => 'Reason',
  'admin_payments_refund_processed' => 'Refund processed.',
  'admin_payments_refund_invalid' => 'Invalid refund amount.',
  'admin_payments_no_transactions' => 'No transactions found.',
  'admin_payments_stripe_failed' => 'Stripe refund failed: ',
  'order_transaction_id' => 'Transaction ID',
  'order_refunded' => 'Refunded',

  // Content
  'nav_blog' => 'Blog',
  'nav_faq' => 'FAQ',
  'nav_policies' => 'Policies',
  'admin_blog' => 'Blog',
  'admin_blog_all' => 'All Posts',
  'admin_blog_new' => 'New Post',
  'admin_blog_edit' => 'Edit Post',
  'admin_blog_created' => 'Post created.',
  'admin_blog_updated' => 'Post updated.',
  'admin_blog_deleted' => 'Post deleted.',
  'admin_faq' => 'FAQ',
  'admin_faq_all' => 'All FAQs',
  'admin_faq_new' => 'New FAQ',
  'admin_faq_edit' => 'Edit FAQ',
  'admin_faq_created' => 'FAQ created.',
  'admin_faq_updated' => 'FAQ updated.',
  'admin_faq_deleted' => 'FAQ deleted.',
  'admin_policies' => 'Policies',
  'admin_policies_all' => 'All Pages',
  'admin_policies_new' => 'New Page',
  'admin_policies_edit' => 'Edit Page',
  'admin_policies_created' => 'Policy created.',
  'admin_policies_updated' => 'Policy updated.',
  'admin_policies_deleted' => 'Policy deleted.',
  'admin_landing' => 'Landing Pages',
  'admin_landing_all' => 'All Landing Pages',
  'admin_landing_new' => 'New Page',
  'admin_landing_edit' => 'Edit Page',
  'admin_landing_created' => 'Landing page created.',
  'admin_landing_updated' => 'Landing page updated.',
  'admin_landing_deleted' => 'Landing page deleted.',

  // Reports
  'admin_reports' => 'Reports',
  'admin_reports_sales' => 'Sales',
  'admin_reports_inventory' => 'Inventory',
  'admin_reports_products' => 'Products',
  'admin_reports_customers' => 'Customers',
  'admin_reports_revenue_30d' => 'Total Revenue (30d)',
  'admin_reports_orders_30d' => 'Orders (30d)',
  'admin_reports_avg_order' => 'Avg Order Value',
  'admin_reports_daily_revenue' => 'Daily Revenue (Last 30 Days)',
  'admin_reports_orders_by_status' => 'Orders by Status',
  'admin_reports_payment_methods' => 'Payment Methods',
  'admin_reports_top_products' => 'Top Selling Products',
  'admin_reports_total_products' => 'Total Products',
  'admin_reports_stock_value' => 'Stock Value',
  'admin_reports_out_of_stock' => 'Out of Stock',
  'admin_reports_low_stock' => 'Low Stock Products',
  'admin_reports_movements' => 'Inventory Movements',
  'admin_reports_by_category' => 'Products by Category',
  'admin_reports_top_rated' => 'Top Rated Products',
  'admin_reports_total_customers' => 'Total Customers',
  'admin_reports_top_spender' => 'Top Spender',
  'admin_reports_new_year' => 'New This Year',
  'admin_reports_new_monthly' => 'New Customers (Monthly)',
  'admin_reports_top_customers' => 'Top Customers by Spend',
  'admin_reports_customer_activity' => 'Customer Activity by Order Status',

  // Errors
  'error_not_found' => 'Page not found.',
  'error_forbidden' => 'Access denied.',
  'error_required' => 'This field is required.',
  'checkout_invalid_email' => 'Invalid email address.',

  // Newsletter
  'newsletter_success' => 'Thanks for subscribing!',
  'newsletter_exists' => 'This email is already subscribed.',

  // General
  'search' => 'Search',
  'search_no_results' => 'No products found',
  'search_view_all' => 'View all results',
  'loading' => 'Loading...',
  'save' => 'Save',
  'cancel' => 'Cancel',
  'delete' => 'Delete',
  'edit' => 'Edit',
  'back' => 'Back',
  'dark_mode' => 'Dark Mode',
  'light_mode' => 'Light Mode',
  'language_switcher' => 'Language',
];
